import {MigrationInterface, QueryRunner} from "typeorm";

export class UpdateSchema1589027910651 implements MigrationInterface {
    name = 'UpdateSchema1589027910651'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "service_variant" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "price" integer NOT NULL, "specialPrice" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "serviceId" integer, CONSTRAINT "PK_b12412145892165d55d7091cb9e" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TYPE "service_available_enum" AS ENUM('anyone', 'male', 'female')`, undefined);
        await queryRunner.query(`CREATE TABLE "service" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "descriptions" character varying NOT NULL, "available" "service_available_enum" NOT NULL DEFAULT 'anyone', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" integer, CONSTRAINT "PK_85a21558c006647cd76fdce044b" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "class_session" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "price" integer NOT NULL, "specialPrice" integer NOT NULL, "startDate" character varying NOT NULL, "endDate" character varying NOT NULL, "days" character varying NOT NULL, "startTime" character varying NOT NULL, "duration" integer NOT NULL, "blockingDates" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "classId" integer, CONSTRAINT "PK_a3d6e3f59db21b19a3b6eb908d9" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TYPE "class_available_enum" AS ENUM('anyone', 'male', 'female')`, undefined);
        await queryRunner.query(`CREATE TABLE "class" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "descriptions" character varying NOT NULL, "available" "class_available_enum" NOT NULL DEFAULT 'anyone', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" integer, CONSTRAINT "PK_0b9024d21bdfba8b1bd1c300eae" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "voucher" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "descriptions" character varying NOT NULL, "price" integer NOT NULL, "startDate" character varying NOT NULL, "endDate" character varying NOT NULL, "messages" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" integer, CONSTRAINT "PK_677ae75f380e81c2f103a57ffaf" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "membership" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "descriptions" character varying NOT NULL, "price" integer NOT NULL, "specialPrice" integer NOT NULL, "slot" integer NOT NULL, "isUnlimited" boolean NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" integer, CONSTRAINT "PK_83c1afebef3059472e7c37e8de8" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "asset" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "descriptions" character varying NOT NULL, "price" integer NOT NULL, "specialPrice" integer NOT NULL, "stock" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" integer, CONSTRAINT "PK_1209d107fe21482beaea51b745e" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TYPE "plan_periodic_enum" AS ENUM('1#daily', '2#weekly', '3#monthly', '4#weekend', '5#weekdays', '6#custom')`, undefined);
        await queryRunner.query(`CREATE TYPE "plan_type_enum" AS ENUM('1#product', '2#service', '3#class', '4#package', '5#asset', '6#deals', '7#membership')`, undefined);
        await queryRunner.query(`CREATE TABLE "plan" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "descriptions" character varying NOT NULL, "periodic" "plan_periodic_enum" NOT NULL DEFAULT '3#monthly', "type" "plan_type_enum" NOT NULL DEFAULT '1#product', "days" character varying NOT NULL, "startDate" character varying NOT NULL, "endDate" character varying NOT NULL, "time" character varying NOT NULL, "notes" character varying NOT NULL, "address" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" integer, CONSTRAINT "PK_54a2b686aed3b637654bf7ddbb3" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TYPE "order_type_enum" AS ENUM('1#sameday', '2#scheduled', '3#takeout', '4#booking', '5#voucher', '6#class', '7#plan', '8#dinein', '9#rent', '10#member', '11#deal')`, undefined);
        await queryRunner.query(`CREATE TABLE "order" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "descriptions" character varying NOT NULL, "type" "order_type_enum" NOT NULL DEFAULT '7#plan', "date" character varying NOT NULL, "time" character varying NOT NULL, "notes" character varying NOT NULL, "address" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" integer, CONSTRAINT "PK_1031171c13130102495201e3e20" PRIMARY KEY ("id"))`, undefined);
        await queryRunner.query(`CREATE TABLE "plan_products_product" ("planId" integer NOT NULL, "productId" integer NOT NULL, CONSTRAINT "PK_8532a4b828414a4f158964e2dcf" PRIMARY KEY ("planId", "productId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_480da045d65c0e09361fca529e" ON "plan_products_product" ("planId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_885902dbe65e3e44e250e4d40e" ON "plan_products_product" ("productId") `, undefined);
        await queryRunner.query(`CREATE TABLE "plan_services_service" ("planId" integer NOT NULL, "serviceId" integer NOT NULL, CONSTRAINT "PK_0e2a86692c5a5ee668bb5f1957c" PRIMARY KEY ("planId", "serviceId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_b8fe726a5272b11e674e3ba109" ON "plan_services_service" ("planId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_f198907b5d6fc74585f42d2890" ON "plan_services_service" ("serviceId") `, undefined);
        await queryRunner.query(`CREATE TABLE "plan_classes_class" ("planId" integer NOT NULL, "classId" integer NOT NULL, CONSTRAINT "PK_7f6a60f6952ed1b3bd5b8da21ce" PRIMARY KEY ("planId", "classId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_ece595c48aadb9edf17d78a08c" ON "plan_classes_class" ("planId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_39f4a030a3f75c458e44c14278" ON "plan_classes_class" ("classId") `, undefined);
        await queryRunner.query(`CREATE TABLE "plan_packages_package" ("planId" integer NOT NULL, "packageId" integer NOT NULL, CONSTRAINT "PK_8c1ef849ea660bba784cab09449" PRIMARY KEY ("planId", "packageId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_959df15ad2ce89318a21a56d51" ON "plan_packages_package" ("planId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_64512d8c98e611afaac1da1752" ON "plan_packages_package" ("packageId") `, undefined);
        await queryRunner.query(`CREATE TABLE "plan_assets_asset" ("planId" integer NOT NULL, "assetId" integer NOT NULL, CONSTRAINT "PK_67df12d07cb1e534d3ebc1abc40" PRIMARY KEY ("planId", "assetId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_87bd0e5f0346bf36e5528037d0" ON "plan_assets_asset" ("planId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_10b0805de3964deb34ce5edc6b" ON "plan_assets_asset" ("assetId") `, undefined);
        await queryRunner.query(`CREATE TABLE "plan_memberships_membership" ("planId" integer NOT NULL, "membershipId" integer NOT NULL, CONSTRAINT "PK_7788ebb0e4c11c78625273a28fc" PRIMARY KEY ("planId", "membershipId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_4ad123581352eda47465295d20" ON "plan_memberships_membership" ("planId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_0adf359c184b83c8d3eeddda38" ON "plan_memberships_membership" ("membershipId") `, undefined);
        await queryRunner.query(`CREATE TABLE "order_products_product" ("orderId" integer NOT NULL, "productId" integer NOT NULL, CONSTRAINT "PK_59f5d41216418eba313ed3c7d7c" PRIMARY KEY ("orderId", "productId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_1f9ea0b0e59e0d98ade4f2d5e9" ON "order_products_product" ("orderId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_d6c66c08b9c7e84a1b657797df" ON "order_products_product" ("productId") `, undefined);
        await queryRunner.query(`CREATE TABLE "order_services_service" ("orderId" integer NOT NULL, "serviceId" integer NOT NULL, CONSTRAINT "PK_fdc94febd644344d9d56b681fff" PRIMARY KEY ("orderId", "serviceId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_5766acb0a87a7742d7b74d3b0b" ON "order_services_service" ("orderId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_52f4ebd3e616a18e7e9afe48f9" ON "order_services_service" ("serviceId") `, undefined);
        await queryRunner.query(`CREATE TABLE "order_classes_class" ("orderId" integer NOT NULL, "classId" integer NOT NULL, CONSTRAINT "PK_628d7c0ed202a78592387a14e5e" PRIMARY KEY ("orderId", "classId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_814d3d91b5991a82f164925434" ON "order_classes_class" ("orderId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_057714294bed91c1cd24d8fe79" ON "order_classes_class" ("classId") `, undefined);
        await queryRunner.query(`CREATE TABLE "order_packages_package" ("orderId" integer NOT NULL, "packageId" integer NOT NULL, CONSTRAINT "PK_604f65c81b258a686a73786dfdd" PRIMARY KEY ("orderId", "packageId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_b8fbda3de3e6a30caee9fe5c62" ON "order_packages_package" ("orderId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_a616b93361b7dc18fe21880add" ON "order_packages_package" ("packageId") `, undefined);
        await queryRunner.query(`CREATE TABLE "order_assets_asset" ("orderId" integer NOT NULL, "assetId" integer NOT NULL, CONSTRAINT "PK_e379f8402007559f1a0e272f4d4" PRIMARY KEY ("orderId", "assetId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_780ab371ddf814235e8ad057b3" ON "order_assets_asset" ("orderId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_34842421ec7f8832e8b5187fec" ON "order_assets_asset" ("assetId") `, undefined);
        await queryRunner.query(`CREATE TABLE "order_vouchers_voucher" ("orderId" integer NOT NULL, "voucherId" integer NOT NULL, CONSTRAINT "PK_a6451c33341e9342d9b0a6f3642" PRIMARY KEY ("orderId", "voucherId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_92e90f546775e5991ddbd3f4fb" ON "order_vouchers_voucher" ("orderId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_29f0592188939566175fc27f7b" ON "order_vouchers_voucher" ("voucherId") `, undefined);
        await queryRunner.query(`CREATE TABLE "order_plans_plan" ("orderId" integer NOT NULL, "planId" integer NOT NULL, CONSTRAINT "PK_ad744d288a610490991ba6a3b37" PRIMARY KEY ("orderId", "planId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_1dc3b0dad658c03e67cd381199" ON "order_plans_plan" ("orderId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_ee1ced4bbe2b3f012b3b9fc1c4" ON "order_plans_plan" ("planId") `, undefined);
        await queryRunner.query(`CREATE TABLE "order_memberships_membership" ("orderId" integer NOT NULL, "membershipId" integer NOT NULL, CONSTRAINT "PK_05fc62eb2337e5194b81d6b27dd" PRIMARY KEY ("orderId", "membershipId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_d3e1a51deb6c48ae7ee4307aac" ON "order_memberships_membership" ("orderId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_c6713e416937e2194b941a9d6b" ON "order_memberships_membership" ("membershipId") `, undefined);
        await queryRunner.query(`ALTER TABLE "service_variant" ADD CONSTRAINT "FK_82f66618745b07e7b2b6fac7c27" FOREIGN KEY ("serviceId") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "service" ADD CONSTRAINT "FK_02fbdab4c697f74792472b88546" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "class_session" ADD CONSTRAINT "FK_e96a68f8862b080d418f7b4f326" FOREIGN KEY ("classId") REFERENCES "class"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "class" ADD CONSTRAINT "FK_75c97180db0c7b6f19d8bb4eb24" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "voucher" ADD CONSTRAINT "FK_4ad7f60e45b10b9c9d10a5bb7ff" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "membership" ADD CONSTRAINT "FK_a3548976d3416dcaeac8b69ce03" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "asset" ADD CONSTRAINT "FK_41ea4c15e17bb2bf3a6d52f5e1c" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "plan" ADD CONSTRAINT "FK_748cf73720bba1398ac405014d5" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_75c9ce255f89db219917013e0fc" FOREIGN KEY ("companyId") REFERENCES "company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_products_product" ADD CONSTRAINT "FK_480da045d65c0e09361fca529e7" FOREIGN KEY ("planId") REFERENCES "plan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_products_product" ADD CONSTRAINT "FK_885902dbe65e3e44e250e4d40e5" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_services_service" ADD CONSTRAINT "FK_b8fe726a5272b11e674e3ba1097" FOREIGN KEY ("planId") REFERENCES "plan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_services_service" ADD CONSTRAINT "FK_f198907b5d6fc74585f42d28904" FOREIGN KEY ("serviceId") REFERENCES "service"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_classes_class" ADD CONSTRAINT "FK_ece595c48aadb9edf17d78a08c9" FOREIGN KEY ("planId") REFERENCES "plan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_classes_class" ADD CONSTRAINT "FK_39f4a030a3f75c458e44c142782" FOREIGN KEY ("classId") REFERENCES "class"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_packages_package" ADD CONSTRAINT "FK_959df15ad2ce89318a21a56d513" FOREIGN KEY ("planId") REFERENCES "plan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_packages_package" ADD CONSTRAINT "FK_64512d8c98e611afaac1da17524" FOREIGN KEY ("packageId") REFERENCES "package"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_assets_asset" ADD CONSTRAINT "FK_87bd0e5f0346bf36e5528037d08" FOREIGN KEY ("planId") REFERENCES "plan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_assets_asset" ADD CONSTRAINT "FK_10b0805de3964deb34ce5edc6bb" FOREIGN KEY ("assetId") REFERENCES "asset"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_memberships_membership" ADD CONSTRAINT "FK_4ad123581352eda47465295d200" FOREIGN KEY ("planId") REFERENCES "plan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_memberships_membership" ADD CONSTRAINT "FK_0adf359c184b83c8d3eeddda386" FOREIGN KEY ("membershipId") REFERENCES "membership"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "order_products_product" ADD CONSTRAINT "FK_1f9ea0b0e59e0d98ade4f2d5e99" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "order_products_product" ADD CONSTRAINT "FK_d6c66c08b9c7e84a1b657797dff" FOREIGN KEY ("productId") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "order_services_service" ADD CONSTRAINT "FK_5766acb0a87a7742d7b74d3b0b8" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "order_services_service" ADD CONSTRAINT "FK_52f4ebd3e616a18e7e9afe48f9d" FOREIGN KEY ("serviceId") REFERENCES "service"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "order_classes_class" ADD CONSTRAINT "FK_814d3d91b5991a82f1649254343" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "order_classes_class" ADD CONSTRAINT "FK_057714294bed91c1cd24d8fe797" FOREIGN KEY ("classId") REFERENCES "class"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "order_packages_package" ADD CONSTRAINT "FK_b8fbda3de3e6a30caee9fe5c623" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "order_packages_package" ADD CONSTRAINT "FK_a616b93361b7dc18fe21880addf" FOREIGN KEY ("packageId") REFERENCES "package"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "order_assets_asset" ADD CONSTRAINT "FK_780ab371ddf814235e8ad057b3a" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "order_assets_asset" ADD CONSTRAINT "FK_34842421ec7f8832e8b5187fec1" FOREIGN KEY ("assetId") REFERENCES "asset"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "order_vouchers_voucher" ADD CONSTRAINT "FK_92e90f546775e5991ddbd3f4fb9" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "order_vouchers_voucher" ADD CONSTRAINT "FK_29f0592188939566175fc27f7b8" FOREIGN KEY ("voucherId") REFERENCES "voucher"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "order_plans_plan" ADD CONSTRAINT "FK_1dc3b0dad658c03e67cd3811996" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "order_plans_plan" ADD CONSTRAINT "FK_ee1ced4bbe2b3f012b3b9fc1c4d" FOREIGN KEY ("planId") REFERENCES "plan"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "order_memberships_membership" ADD CONSTRAINT "FK_d3e1a51deb6c48ae7ee4307aacc" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
        await queryRunner.query(`ALTER TABLE "order_memberships_membership" ADD CONSTRAINT "FK_c6713e416937e2194b941a9d6b0" FOREIGN KEY ("membershipId") REFERENCES "membership"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "order_memberships_membership" DROP CONSTRAINT "FK_c6713e416937e2194b941a9d6b0"`, undefined);
        await queryRunner.query(`ALTER TABLE "order_memberships_membership" DROP CONSTRAINT "FK_d3e1a51deb6c48ae7ee4307aacc"`, undefined);
        await queryRunner.query(`ALTER TABLE "order_plans_plan" DROP CONSTRAINT "FK_ee1ced4bbe2b3f012b3b9fc1c4d"`, undefined);
        await queryRunner.query(`ALTER TABLE "order_plans_plan" DROP CONSTRAINT "FK_1dc3b0dad658c03e67cd3811996"`, undefined);
        await queryRunner.query(`ALTER TABLE "order_vouchers_voucher" DROP CONSTRAINT "FK_29f0592188939566175fc27f7b8"`, undefined);
        await queryRunner.query(`ALTER TABLE "order_vouchers_voucher" DROP CONSTRAINT "FK_92e90f546775e5991ddbd3f4fb9"`, undefined);
        await queryRunner.query(`ALTER TABLE "order_assets_asset" DROP CONSTRAINT "FK_34842421ec7f8832e8b5187fec1"`, undefined);
        await queryRunner.query(`ALTER TABLE "order_assets_asset" DROP CONSTRAINT "FK_780ab371ddf814235e8ad057b3a"`, undefined);
        await queryRunner.query(`ALTER TABLE "order_packages_package" DROP CONSTRAINT "FK_a616b93361b7dc18fe21880addf"`, undefined);
        await queryRunner.query(`ALTER TABLE "order_packages_package" DROP CONSTRAINT "FK_b8fbda3de3e6a30caee9fe5c623"`, undefined);
        await queryRunner.query(`ALTER TABLE "order_classes_class" DROP CONSTRAINT "FK_057714294bed91c1cd24d8fe797"`, undefined);
        await queryRunner.query(`ALTER TABLE "order_classes_class" DROP CONSTRAINT "FK_814d3d91b5991a82f1649254343"`, undefined);
        await queryRunner.query(`ALTER TABLE "order_services_service" DROP CONSTRAINT "FK_52f4ebd3e616a18e7e9afe48f9d"`, undefined);
        await queryRunner.query(`ALTER TABLE "order_services_service" DROP CONSTRAINT "FK_5766acb0a87a7742d7b74d3b0b8"`, undefined);
        await queryRunner.query(`ALTER TABLE "order_products_product" DROP CONSTRAINT "FK_d6c66c08b9c7e84a1b657797dff"`, undefined);
        await queryRunner.query(`ALTER TABLE "order_products_product" DROP CONSTRAINT "FK_1f9ea0b0e59e0d98ade4f2d5e99"`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_memberships_membership" DROP CONSTRAINT "FK_0adf359c184b83c8d3eeddda386"`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_memberships_membership" DROP CONSTRAINT "FK_4ad123581352eda47465295d200"`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_assets_asset" DROP CONSTRAINT "FK_10b0805de3964deb34ce5edc6bb"`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_assets_asset" DROP CONSTRAINT "FK_87bd0e5f0346bf36e5528037d08"`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_packages_package" DROP CONSTRAINT "FK_64512d8c98e611afaac1da17524"`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_packages_package" DROP CONSTRAINT "FK_959df15ad2ce89318a21a56d513"`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_classes_class" DROP CONSTRAINT "FK_39f4a030a3f75c458e44c142782"`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_classes_class" DROP CONSTRAINT "FK_ece595c48aadb9edf17d78a08c9"`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_services_service" DROP CONSTRAINT "FK_f198907b5d6fc74585f42d28904"`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_services_service" DROP CONSTRAINT "FK_b8fe726a5272b11e674e3ba1097"`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_products_product" DROP CONSTRAINT "FK_885902dbe65e3e44e250e4d40e5"`, undefined);
        await queryRunner.query(`ALTER TABLE "plan_products_product" DROP CONSTRAINT "FK_480da045d65c0e09361fca529e7"`, undefined);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_75c9ce255f89db219917013e0fc"`, undefined);
        await queryRunner.query(`ALTER TABLE "plan" DROP CONSTRAINT "FK_748cf73720bba1398ac405014d5"`, undefined);
        await queryRunner.query(`ALTER TABLE "asset" DROP CONSTRAINT "FK_41ea4c15e17bb2bf3a6d52f5e1c"`, undefined);
        await queryRunner.query(`ALTER TABLE "membership" DROP CONSTRAINT "FK_a3548976d3416dcaeac8b69ce03"`, undefined);
        await queryRunner.query(`ALTER TABLE "voucher" DROP CONSTRAINT "FK_4ad7f60e45b10b9c9d10a5bb7ff"`, undefined);
        await queryRunner.query(`ALTER TABLE "class" DROP CONSTRAINT "FK_75c97180db0c7b6f19d8bb4eb24"`, undefined);
        await queryRunner.query(`ALTER TABLE "class_session" DROP CONSTRAINT "FK_e96a68f8862b080d418f7b4f326"`, undefined);
        await queryRunner.query(`ALTER TABLE "service" DROP CONSTRAINT "FK_02fbdab4c697f74792472b88546"`, undefined);
        await queryRunner.query(`ALTER TABLE "service_variant" DROP CONSTRAINT "FK_82f66618745b07e7b2b6fac7c27"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_c6713e416937e2194b941a9d6b"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_d3e1a51deb6c48ae7ee4307aac"`, undefined);
        await queryRunner.query(`DROP TABLE "order_memberships_membership"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_ee1ced4bbe2b3f012b3b9fc1c4"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_1dc3b0dad658c03e67cd381199"`, undefined);
        await queryRunner.query(`DROP TABLE "order_plans_plan"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_29f0592188939566175fc27f7b"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_92e90f546775e5991ddbd3f4fb"`, undefined);
        await queryRunner.query(`DROP TABLE "order_vouchers_voucher"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_34842421ec7f8832e8b5187fec"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_780ab371ddf814235e8ad057b3"`, undefined);
        await queryRunner.query(`DROP TABLE "order_assets_asset"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_a616b93361b7dc18fe21880add"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_b8fbda3de3e6a30caee9fe5c62"`, undefined);
        await queryRunner.query(`DROP TABLE "order_packages_package"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_057714294bed91c1cd24d8fe79"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_814d3d91b5991a82f164925434"`, undefined);
        await queryRunner.query(`DROP TABLE "order_classes_class"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_52f4ebd3e616a18e7e9afe48f9"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_5766acb0a87a7742d7b74d3b0b"`, undefined);
        await queryRunner.query(`DROP TABLE "order_services_service"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_d6c66c08b9c7e84a1b657797df"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_1f9ea0b0e59e0d98ade4f2d5e9"`, undefined);
        await queryRunner.query(`DROP TABLE "order_products_product"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_0adf359c184b83c8d3eeddda38"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_4ad123581352eda47465295d20"`, undefined);
        await queryRunner.query(`DROP TABLE "plan_memberships_membership"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_10b0805de3964deb34ce5edc6b"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_87bd0e5f0346bf36e5528037d0"`, undefined);
        await queryRunner.query(`DROP TABLE "plan_assets_asset"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_64512d8c98e611afaac1da1752"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_959df15ad2ce89318a21a56d51"`, undefined);
        await queryRunner.query(`DROP TABLE "plan_packages_package"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_39f4a030a3f75c458e44c14278"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_ece595c48aadb9edf17d78a08c"`, undefined);
        await queryRunner.query(`DROP TABLE "plan_classes_class"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_f198907b5d6fc74585f42d2890"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_b8fe726a5272b11e674e3ba109"`, undefined);
        await queryRunner.query(`DROP TABLE "plan_services_service"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_885902dbe65e3e44e250e4d40e"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_480da045d65c0e09361fca529e"`, undefined);
        await queryRunner.query(`DROP TABLE "plan_products_product"`, undefined);
        await queryRunner.query(`DROP TABLE "order"`, undefined);
        await queryRunner.query(`DROP TYPE "order_type_enum"`, undefined);
        await queryRunner.query(`DROP TABLE "plan"`, undefined);
        await queryRunner.query(`DROP TYPE "plan_type_enum"`, undefined);
        await queryRunner.query(`DROP TYPE "plan_periodic_enum"`, undefined);
        await queryRunner.query(`DROP TABLE "asset"`, undefined);
        await queryRunner.query(`DROP TABLE "membership"`, undefined);
        await queryRunner.query(`DROP TABLE "voucher"`, undefined);
        await queryRunner.query(`DROP TABLE "class"`, undefined);
        await queryRunner.query(`DROP TYPE "class_available_enum"`, undefined);
        await queryRunner.query(`DROP TABLE "class_session"`, undefined);
        await queryRunner.query(`DROP TABLE "service"`, undefined);
        await queryRunner.query(`DROP TYPE "service_available_enum"`, undefined);
        await queryRunner.query(`DROP TABLE "service_variant"`, undefined);
    }

}
